import type { Metadata } from 'next'
import './global.css'

export const metadata: Metadata = {
  title: 'FYP-COBA2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}